-- Octo - GitHub issues and PRs in Neovim
return {
  'pwntester/octo.nvim',
  cmd = 'Octo',
  dependencies = {
    'nvim-lua/plenary.nvim',
    'nvim-telescope/telescope.nvim',
    'nvim-tree/nvim-web-devicons',
  },
  opts = {
    use_local_fs = false,
    enable_builtin = false,
    default_remote = { 'upstream', 'origin' },
    default_merge_method = 'commit',
    ssh_aliases = {},
    reaction_viewer_hint_icon = '',
    user_icon = ' ',
    timeline_marker = '',
    timeline_indent = '2',
    right_bubble_delimiter = '',
    left_bubble_delimiter = '',
    github_hostname = '',
    snippet_context_lines = 4,
    gh_env = {},
    timeout = 5000,
    ui = {
      use_signcolumn = true,
      use_signstatus = true,
    },
    issues = {
      order_by = {
        field = 'CREATED_AT',
        direction = 'DESC',
      },
    },
    pull_requests = {
      order_by = {
        field = 'CREATED_AT',
        direction = 'DESC',
      },
      always_select_remote_on_create = false,
    },
    file_panel = {
      size = 10,
      use_icons = true,
    },
    mappings = {
      issue = {
        close_issue = { lhs = '<leader>ic', desc = '[I]ssue [C]lose' },
        reopen_issue = { lhs = '<leader>io', desc = '[I]ssue Re[o]pen' },
        list_issues = { lhs = '<leader>il', desc = '[I]ssue [L]ist' },
        reload = { lhs = '<C-r>', desc = 'Reload' },
        open_in_browser = { lhs = '<C-b>', desc = 'Open in browser' },
        copy_url = { lhs = '<C-y>', desc = 'Copy URL' },
        add_assignee = { lhs = '<leader>aa', desc = '[A]dd [A]ssignee' },
        remove_assignee = { lhs = '<leader>ad', desc = '[A]ssignee [D]elete' },
        create_label = { lhs = '<leader>lc', desc = '[L]abel [C]reate' },
        add_label = { lhs = '<leader>la', desc = '[L]abel [A]dd' },
        remove_label = { lhs = '<leader>ld', desc = '[L]abel [D]elete' },
        goto_issue = { lhs = '<leader>gi', desc = '[G]o to [I]ssue' },
        add_comment = { lhs = '<leader>ca', desc = '[C]omment [A]dd' },
        delete_comment = { lhs = '<leader>cd', desc = '[C]omment [D]elete' },
        next_comment = { lhs = ']c', desc = 'Next comment' },
        prev_comment = { lhs = '[c', desc = 'Previous comment' },
        react_hooray = { lhs = '<leader>rp', desc = '[R]eact [P]arty' },
        react_heart = { lhs = '<leader>rh', desc = '[R]eact [H]eart' },
        react_eyes = { lhs = '<leader>re', desc = '[R]eact [E]yes' },
        react_thumbs_up = { lhs = '<leader>r+', desc = '[R]eact Thumbs Up' },
        react_thumbs_down = { lhs = '<leader>r-', desc = '[R]eact Thumbs Down' },
        react_rocket = { lhs = '<leader>rr', desc = '[R]eact [R]ocket' },
        react_laugh = { lhs = '<leader>rl', desc = '[R]eact [L]augh' },
        react_confused = { lhs = '<leader>rc', desc = '[R]eact [C]onfused' },
      },
      pull_request = {
        checkout_pr = { lhs = '<leader>po', desc = '[P]R Check[o]ut' },
        merge_pr = { lhs = '<leader>pm', desc = '[P]R [M]erge' },
        list_commits = { lhs = '<leader>pc', desc = '[P]R [C]ommits' },
        list_changed_files = { lhs = '<leader>pf', desc = '[P]R [F]iles' },
        show_pr_diff = { lhs = '<leader>pd', desc = '[P]R [D]iff' },
        add_reviewer = { lhs = '<leader>va', desc = 'Re[v]iewer [A]dd' },
        remove_reviewer = { lhs = '<leader>vd', desc = 'Re[v]iewer [D]elete' },
        close_issue = { lhs = '<leader>ic', desc = '[I]ssue [C]lose' },
        reopen_issue = { lhs = '<leader>io', desc = '[I]ssue Re[o]pen' },
        list_issues = { lhs = '<leader>il', desc = '[I]ssue [L]ist' },
        reload = { lhs = '<C-r>', desc = 'Reload' },
        open_in_browser = { lhs = '<C-b>', desc = 'Open in browser' },
        copy_url = { lhs = '<C-y>', desc = 'Copy URL' },
        goto_file = { lhs = 'gf', desc = 'Go to file' },
        add_assignee = { lhs = '<leader>aa', desc = '[A]dd [A]ssignee' },
        remove_assignee = { lhs = '<leader>ad', desc = '[A]ssignee [D]elete' },
        create_label = { lhs = '<leader>lc', desc = '[L]abel [C]reate' },
        add_label = { lhs = '<leader>la', desc = '[L]abel [A]dd' },
        remove_label = { lhs = '<leader>ld', desc = '[L]abel [D]elete' },
        goto_issue = { lhs = '<leader>gi', desc = '[G]o to [I]ssue' },
        add_comment = { lhs = '<leader>ca', desc = '[C]omment [A]dd' },
        delete_comment = { lhs = '<leader>cd', desc = '[C]omment [D]elete' },
        next_comment = { lhs = ']c', desc = 'Next comment' },
        prev_comment = { lhs = '[c', desc = 'Previous comment' },
        react_hooray = { lhs = '<leader>rp', desc = '[R]eact [P]arty' },
        react_heart = { lhs = '<leader>rh', desc = '[R]eact [H]eart' },
        react_eyes = { lhs = '<leader>re', desc = '[R]eact [E]yes' },
        react_thumbs_up = { lhs = '<leader>r+', desc = '[R]eact Thumbs Up' },
        react_thumbs_down = { lhs = '<leader>r-', desc = '[R]eact Thumbs Down' },
        react_rocket = { lhs = '<leader>rr', desc = '[R]eact [R]ocket' },
        react_laugh = { lhs = '<leader>rl', desc = '[R]eact [L]augh' },
        react_confused = { lhs = '<leader>rc', desc = '[R]eact [C]onfused' },
        review_start = { lhs = '<leader>vs', desc = 'Re[v]iew [S]tart' },
        review_resume = { lhs = '<leader>vr', desc = 'Re[v]iew [R]esume' },
      },
      review_thread = {
        goto_issue = { lhs = '<leader>gi', desc = '[G]o to [I]ssue' },
        add_comment = { lhs = '<leader>ca', desc = '[C]omment [A]dd' },
        add_suggestion = { lhs = '<leader>sa', desc = '[S]uggestion [A]dd' },
        delete_comment = { lhs = '<leader>cd', desc = '[C]omment [D]elete' },
        next_comment = { lhs = ']c', desc = 'Next comment' },
        prev_comment = { lhs = '[c', desc = 'Previous comment' },
        select_next_entry = { lhs = ']q', desc = 'Next entry' },
        select_prev_entry = { lhs = '[q', desc = 'Previous entry' },
        close_review_tab = { lhs = '<C-c>', desc = 'Close review tab' },
        react_hooray = { lhs = '<leader>rp', desc = '[R]eact [P]arty' },
        react_heart = { lhs = '<leader>rh', desc = '[R]eact [H]eart' },
        react_eyes = { lhs = '<leader>re', desc = '[R]eact [E]yes' },
        react_thumbs_up = { lhs = '<leader>r+', desc = '[R]eact Thumbs Up' },
        react_thumbs_down = { lhs = '<leader>r-', desc = '[R]eact Thumbs Down' },
        react_rocket = { lhs = '<leader>rr', desc = '[R]eact [R]ocket' },
        react_laugh = { lhs = '<leader>rl', desc = '[R]eact [L]augh' },
        react_confused = { lhs = '<leader>rc', desc = '[R]eact [C]onfused' },
      },
      submit_win = {
        approve_review = { lhs = '<C-a>', desc = 'Approve review' },
        comment_review = { lhs = '<C-m>', desc = 'Comment review' },
        request_changes = { lhs = '<C-r>', desc = 'Request changes' },
        close_review_tab = { lhs = '<C-c>', desc = 'Close review tab' },
      },
      review_diff = {
        submit_review = { lhs = '<leader>vs', desc = 're[V]iew [S]ubmit' },
        discard_review = { lhs = '<leader>vd', desc = 're[V]iew [D]iscard' },
        add_review_comment = { lhs = '<leader>ca', desc = '[C]omment [A]dd' },
        add_review_suggestion = { lhs = '<leader>sa', desc = '[S]uggestion [A]dd' },
        focus_files = { lhs = '<leader>e', desc = 'Focus files' },
        toggle_files = { lhs = '<leader>b', desc = 'Toggle files' },
        next_thread = { lhs = ']t', desc = 'Next thread' },
        prev_thread = { lhs = '[t', desc = 'Previous thread' },
        select_next_entry = { lhs = ']q', desc = 'Next entry' },
        select_prev_entry = { lhs = '[q', desc = 'Previous entry' },
        close_review_tab = { lhs = '<C-c>', desc = 'Close review tab' },
        toggle_viewed = { lhs = '<leader><space>', desc = 'Toggle viewed' },
        goto_file = { lhs = 'gf', desc = 'Go to file' },
      },
      file_panel = {
        submit_review = { lhs = '<leader>vs', desc = 're[V]iew [S]ubmit' },
        discard_review = { lhs = '<leader>vd', desc = 're[V]iew [D]iscard' },
        next_entry = { lhs = 'j', desc = 'Next entry' },
        prev_entry = { lhs = 'k', desc = 'Previous entry' },
        select_entry = { lhs = '<cr>', desc = 'Select entry' },
        refresh_files = { lhs = 'R', desc = 'Refresh files' },
        focus_files = { lhs = '<leader>e', desc = 'Focus files' },
        toggle_files = { lhs = '<leader>b', desc = 'Toggle files' },
        select_next_entry = { lhs = ']q', desc = 'Next entry' },
        select_prev_entry = { lhs = '[q', desc = 'Previous entry' },
        close_review_tab = { lhs = '<C-c>', desc = 'Close review tab' },
        toggle_viewed = { lhs = '<leader><space>', desc = 'Toggle viewed' },
      },
    },
  },
  keys = {
    { '<leader>op', '<cmd>Octo pr list<cr>', desc = '[O]cto [P]R List' },
    { '<leader>oi', '<cmd>Octo issue list<cr>', desc = '[O]cto [I]ssue List' },
    { '<leader>oc', '<cmd>Octo pr create<cr>', desc = '[O]cto PR [C]reate' },
    { '<leader>os', '<cmd>Octo search<cr>', desc = '[O]cto [S]earch' },
  },
}
