-- Overseer - Task runner and job management
return {
  'stevearc/overseer.nvim',
  cmd = {
    'OverseerOpen',
    'OverseerClose',
    'OverseerToggle',
    'OverseerRun',
    'OverseerBuild',
    'OverseerQuickAction',
    'OverseerTaskAction',
  },
  opts = {
    strategy = {
      'toggleterm',
      direction = 'horizontal',
      autos_croll = true,
      quit_on_exit = 'success',
    },
    templates = { 'builtin', 'user.cpp_build', 'user.run_script' },
    task_list = {
      default_detail = 1,
      max_width = { 100, 0.2 },
      min_width = { 40, 0.1 },
      width = nil,
      max_height = { 20, 0.1 },
      min_height = 8,
      height = nil,
      direction = 'bottom',
      bindings = {
        ['?'] = 'ShowHelp',
        ['g?'] = 'ShowHelp',
        ['<CR>'] = 'RunAction',
        ['<C-e>'] = 'Edit',
        ['o'] = 'Open',
        ['<C-v>'] = 'OpenVsplit',
        ['<C-s>'] = 'OpenSplit',
        ['<C-f>'] = 'OpenFloat',
        ['<C-q>'] = 'OpenQuickFix',
        ['p'] = 'TogglePreview',
        ['<C-l>'] = 'IncreaseDetail',
        ['<C-h>'] = 'DecreaseDetail',
        ['L'] = 'IncreaseAllDetail',
        ['H'] = 'DecreaseAllDetail',
        ['['] = 'DecreaseWidth',
        [']'] = 'IncreaseWidth',
        ['{'] = 'PrevTask',
        ['}'] = 'NextTask',
        ['<C-k>'] = 'ScrollOutputUp',
        ['<C-j>'] = 'ScrollOutputDown',
        ['q'] = 'Close',
      },
    },
    form = {
      border = 'rounded',
      zindex = 40,
      min_width = 80,
      max_width = 0.9,
      width = nil,
      min_height = 10,
      max_height = 0.9,
      height = nil,
      win_opts = {
        winblend = 0,
      },
    },
    confirm = {
      border = 'rounded',
      zindex = 40,
      min_width = 20,
      max_width = 0.5,
      width = nil,
      min_height = 6,
      max_height = 0.9,
      height = nil,
      win_opts = {
        winblend = 0,
      },
    },
    task_win = {
      border = 'rounded',
      win_opts = {
        winblend = 0,
      },
    },
    component_aliases = {
      default = {
        { 'display_duration', detail_level = 2 },
        'on_output_summarize',
        'on_exit_set_status',
        'on_complete_notify',
        'on_complete_dispose',
      },
    },
    bundles = {
      save_task_opts = {
        on_save = true,
      },
    },
    dap = false,
    log = {
      {
        type = 'echo',
        level = vim.log.levels.WARN,
      },
      {
        type = 'file',
        filename = 'overseer.log',
        level = vim.log.levels.WARN,
      },
    },
  },
  keys = {
    { '<leader>oo', '<cmd>OverseerToggle<cr>', desc = '[O]verseer T[o]ggle' },
    { '<leader>or', '<cmd>OverseerRun<cr>', desc = '[O]verseer [R]un' },
    { '<leader>oa', '<cmd>OverseerQuickAction<cr>', desc = '[O]verseer [A]ction' },
    { '<leader>ob', '<cmd>OverseerBuild<cr>', desc = '[O]verseer [B]uild' },
    { '<leader>ot', '<cmd>OverseerTaskAction<cr>', desc = '[O]verseer [T]ask Action' },
  },
}
